### ISSUE TITLE
create ToDo example app that showcases `@inlang/sdk-js`

### ISSUE THREAD

**Issue by ivanhofer** [inlang/example#24]
We already have defined the strings, but the actual implenmentation is missing: https://github.com/inlang/example

**Comment by ivanhofer** [comment]
If I do the implementation, can @NilsJacobsen or @NiklasBuchfink apply some great CSS at the end?

**Comment by NilsJacobsen** [comment]
Sure why not😅

**Comment by ivanhofer** [comment]
Here you go: https://github.com/inlang/example/pull/26

**Comment by NilsJacobsen** [comment]
Blocked by: https://github.com/inlang/inlang/issues/938

**Comment by ivanhofer** [comment]
done
